## Auth


##회원가입  (teamId/auth/signup)
# POST https://mogazoa-api.vercel.app/16-05/auth/signUp
# Content-Type: application/json

#{
#     "email": "testjin@email.com", 
#     "nickname": "jin",
#     "password": "12345678", 
#     "passwordConfirmation": "12345678"
# }

# 로그인 (teamId/auth/signin)
# POST https://mogazoa-api.vercel.app/16-05/auth/signIn
# {
#   "email": "testjin@email.com",
#   "password": "12345678"
# }

# 내정보조회 (teamId/users/me)
# GET https://mogazoa-api.vercel.app/16-05/users/me
# Accept: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ODMzLCJ0ZWFtSWQiOiIxNi0wNSIsImlhdCI6MTc1NTgyMjgxNSwiaXNzIjoic3AtbW9nYXpvYSJ9.jzCUVM_UQOA9Kn8w6QaNkMFQl8hS9sBPkwcdIS6pM50

# 상품생성 (teamId/users/me)
# POST https://mogazoa-api.vercel.app/16-05/products
# {
#   "categoryId": 124,
#   "image": "https://gdimg.gmarket.co.kr/2198220959/still/600?ver=1629264687",
#   "description": "지구 최고 주걱 흥부도 이거엔 무한정 맞고싶어 했다고 알려짐",
#   "name": "최강 주걱"
# }